
document.addEventListener("DOMContentLoaded", () => {
  const userGender = localStorage.getItem("rizz_gender");
  const userAge = localStorage.getItem("rizz_age");

  if (userGender && userAge) {
    document.getElementById("user-info").innerText =
      `👋 Welcome! Gender: ${userGender} | Age: ${userAge}`;
  }
});
document.addEventListener("DOMContentLoaded", () => {
  const gender = localStorage.getItem("rizz_gender");
  const age = localStorage.getItem("rizz_age");
  const userInfo = document.getElementById("user-info");

  if (!gender || !age) {
    userInfo.innerText = "👋 Welcome! Start rizzin below 😎";
    return;
  }

  let vibe = "🔥";

  if (age === "13-17") vibe = "😜";
  if (age === "18-24") vibe = "😎";
  if (age === "25-34") vibe = "💪";
  if (age === "35+") vibe = "✨";

  userInfo.innerText = `Welcome ${vibe} | ${gender.toUpperCase()} | ${age}`;
});



// Lines for categories
const lines = {
  playful:[ "Are you a keyboard? Because you’re just my type.",  "Are you a keyboard? Because you’re just my type.",
  "Do you have a map? I keep getting lost in your smile.",
  "Are you Wi-Fi? Because I feel the connection.",
  "Is your name Google? You have everything I’m searching for.",
  "Are you a notification? Because you got my attention.",
  "Are you a magician? Because you make my heart disappear.",
  "Can I take a selfie with you? I want to prove angels exist.",
  "Are you a camera? Every time I see you, I smile.",
  "You must be a campfire… because you’re hot and I want s’more.",
  "Are you French? Because Eiffel for you.",
  "Are you made of copper and tellurium? Because you’re Cu-Te.",
  "If you were a vegetable, you’d be a cute-cumber.",
  "Are you a time traveler? Because I see you in my future.",
  "You must be tired… you’ve been running through my mind.",
  "Are you a star? Because your light brightens my day.",
  "Are you a loan? Because you’ve got my interest.",
  "I must be a snowflake, because I’ve fallen for you.",
  "Are you cake? Because I want a piece of you.",
  "If you were a fruit, you’d be a fine-apple.",
  "Are you sunlight? Because you make my day brighter.",
  "Are you a magician’s assistant? Because you just made my heart disappear.",
  "Are you a puzzle? Because I can’t figure out life without you.",
  "Can I follow you home? Cause my dreams told me to.",
  "Are you a cloud? Because you make my sky brighter.",
  "Are you a phone? Because I can’t stop checking you.",
  "You must be sugar… because you’re sweet.",
  "Are you a ticket? Because you’ve got FINE written all over you.",
  "Are you pizza? Because you’ve got a piece of my heart.",
  "Are you a light switch? You turn me on.",
  "Are you a rainbow? Because you brighten my stormy days.",
  "Are you a donut? Because I donut want anyone else.",
  "Are you an emoji? Because you complete my text.",
  "Are you music? Because you strike a chord in my heart.",
  "Are you a battery? Because you make me feel energized.",
  "Are you a rainbow? Because every moment with you is colorful.",
  "You must be a keyboard, because you add meaning to my life.",
  "Are you a candle? Because you light up my world.",
  "Are you a dictionary? Because you add meaning to my life.",
  "Are you a spark? Because you ignite my soul.",
  "Are you a mirror? Because I see myself in you.",
  "Are you a superhero? Because my heart races around you.",
  "Are you magic? Because everything feels better when you’re around.",
  "Are you a magnet? Because I’m attracted to you.",
  "Are you popcorn? Because you make life more exciting.",
  "Are you a cupcake? Because I want a bite.",
  "Are you confetti? Because you make everything fun.",
  "Are you a balloon? Because you lift me up.",
  "Are you a lighthouse? Because you guide me home.",
  "Are you a pen? Because you write happiness in my life.",
  "Are you a firework? Because you light up my night.",
  "Are you a star? Because I wish for you every night.",
  "Are you a jewel? Because I treasure you.",
  "Are you a flame? Because you ignite my heart.",
  "Are you a cookie? Because I can’t resist you.",
  "Are you a rainbow? Because I find joy when I see you.",
  "Are you a melody? Because life is sweeter with you.",
  "Are you a cupcake? Because you make life sweeter.",
  "Are you coffee? Because you make my morning better.",
  "Are you chocolate? Because I melt when I see you.",
  "Are you a key? Because you unlock my heart.",
  "Are you a breeze? Because you make life feel light.",
  "Are you a rainbow? Because I’m lucky when I see you.",
  "Are you candy? Because life is sweeter with you.",
  "Are you glitter? Because you sparkle everywhere.",
  "Are you a rainbow? Because you’re rare and beautiful.",
  "Are you a pearl? Because I see beauty in you.",
  "Are you a star? Because you light up my sky.",
  "Are you a magic wand? Because you enchant me.",
  "Are you candy floss? Because you make life sweeter.",
  "Are you confetti? Because you make celebrations brighter.",
  "Are you a balloon? Because you lift my spirits.",
  "Are you chocolate? Because you melt my heart.",
  "Are you coffee? Because you keep me awake.",
  "Are you glitter? Because you add sparkle everywhere.",
  "Are you a cupcake? Because I could never get enough of you.",
  "Are you a comet? Because you light up my night.",
  "Are you a sparkler? Because you make life shine.",
  "Are you sugar? Because you’re sweet on me.",
  "Are you a treasure? Because I’ve been searching for you.",
  "Are you a cookie? Because I want a bite.",
  "Are you a candle? Because you make my world glow.",
  "Are you a balloon? Because you lift me up.",
  "Are you a rainbow? Because you brighten my day.",
  "Are you a cupcake? Because life is sweeter with you.",
  "Are you a flame? Because you set my heart on fire.",
  "Are you a light? Because you brighten my darkest days.",
  "Are you a donut? Because I’m sweet on you.",
  "Are you a cupcake? Because I can’t get enough of you.",
  "Are you a bubble? Because life feels lighter with you.",
  "Are you a cupcake? Because you’re the icing on my cake.",
  "Are you a spark? Because you light my fire.",
  "Are you candy? Because I’m addicted to you.",
  "Are you a rainbow? Because you make life colorful.",
  "Are you a coffee? Because you wake up my heart.",
  "Are you a chocolate? Because I melt for you.",
  "Are you a cupcake? Because you make my day sweet.",
  "Are you a star? Because I can’t stop wishing for you.",
  "Are you a cookie? Because you’re my favorite.",
  "Are you a candle? Because you make life brighter.",
  "Are you a balloon? Because I’m floating with you.", "Do you have a map? I keep getting lost in your smile.", "Are you Wi-Fi? Because I feel the connection.", "Is your name Google? You have everything I’m searching for.", "Are you a notification? Because you got my attention." ],
  confident:[ "I don’t chase — I attract.",  "I don’t chase. I attract.",
  "Confidence looks good on me, right?",
  "I know what I want — and it’s you.",
  "I’m not lucky, I’m talented — and so are we together.",
  "I don’t follow trends. I set them.",
  "I don’t compete, I dominate.",
  "I’m not arrogant, I’m aware.",
  "I make things happen, not excuses.",
  "I don’t wait for opportunities, I create them.",
  "I don’t need luck, I’m prepared.",
  "I’m bold, and that’s attractive.",
  "I don’t stress, I impress.",
  "I’m a vibe you can’t ignore.",
  "I don’t hesitate, I execute.",
  "I’m unapologetically me.",
  "I turn dreams into plans.",
  "I’m confident, not cocky.",
  "I know my worth.",
  "I don’t settle, I excel.",
  "I handle pressure like a pro.",
  "I lead, not follow.",
  "I’m fearless when it comes to love.",
  "I speak less, do more.",
  "I’m ambitious and magnetic.",
  "I don’t fake it, I make it.",
  "I’m the energy you want around.",
  "I don’t back down from a challenge.",
  "I’m self-made and unstoppable.",
  "I know what I bring to the table.",
  "I turn heads without trying.",
  "I’m the type they write about.",
  "I don’t wait, I win.",
  "I’m the reason people raise their standards.",
  "I set the bar high and live above it.",
  "I’m driven by passion, not pressure.",
  "I own my choices.",
  "I’m bold enough to love without fear.",
  "I lead with action, not words.",
  "I’m confident in silence and in chaos.",
  "I make every moment count.",
  "I don’t apologize for being myself.",
  "I’m a game-changer, not a player.",
  "I take risks and own the outcome.",
  "I’m proof that confidence attracts.",
  "I make my own luck.",
  "I’m the vibe that inspires.",
  "I don’t need permission to shine.",
  "I’m unstoppable in pursuit of happiness.",
  "I’m the energy that excites.",
  "I’m fearless and magnetic.",
  "I don’t wait for a spotlight, I create one.",
  "I’m unapologetically confident.",
  "I speak my mind with purpose.",
  "I turn heads and hearts.",
  "I attract what matches my energy.",
  "I lead by example.",
  "I’m self-assured and unstoppable.",
  "I trust myself fully.",
  "I don’t worry, I conquer.",
  "I’m bold enough to start, brave enough to finish.",
  "I exude charm without trying.",
  "I stand tall in every room.",
  "I’m confident in my choices.",
  "I radiate positivity and strength.",
  "I’m magnetic without effort.",
  "I’m unapologetic about my ambitions.",
  "I don’t chase, I attract.",
  "I’m the energy people remember.",
  "I handle challenges with grace.",
  "I trust my intuition.",
  "I’m a force of nature.",
  "I inspire without speaking.",
  "I turn confidence into a lifestyle.",
  "I’m unstoppable when I focus.",
  "I lead with heart and mind.",
  "I’m bold enough to love openly.",
  "I’m fearless in pursuit of greatness.",
  "I don’t doubt, I execute.",
  "I rise while others hesitate.",
  "I make my presence felt.",
  "I’m confident and compelling.",
  "I attract success effortlessly.",
  "I stand firm in my beliefs.",
  "I’m ambitious without apology.",
  "I turn obstacles into opportunities.",
  "I shine in my authenticity.",
  "I don’t follow, I lead.",
  "I know my value and own it.",
  "I’m the energy that motivates.",
  "I take initiative and win.",
  "I’m bold in my passions.",
  "I command respect effortlessly.",
  "I don’t blend in, I stand out.",
  "I’m the vibe everyone wants around.",
  "I make every move intentional.",
  "I’m confident in love and life.",
  "I embrace challenges fearlessly.",
  "I’m the standard, not the follower.",
  "I radiate power and charm.",
  "I’m unapologetically ambitious.",
  "I make bold choices and succeed.",
  "I don’t wait for permission, I create it.",
  "I attract what matches my confidence.",
  "I’m fearless, magnetic, and unstoppable.", "I saw you and decided to say hi.", "Confidence looks good on me, right?", "I know what I want.", "I’m not lucky — I’m intentional." ],
  smooth:[ "You walked in and the vibe changed.", "You walked in and the vibe changed.",
  "Let me borrow a moment — I’ll give it back with interest.",
  "You look like trouble… good trouble.",
  "I was blinded by your beauty… I’m going to need a map.",
  "You don’t need a reason to smile, but I’ll give you one.",
  "Is it hot in here, or is it just you?",
  "You’ve got a smile that stops time.",
  "I didn’t know what perfection looked like until I met you.",
  "Are you a sunset? Because you make everything better.",
  "Your energy is contagious.",
  "I’m not flirting… I’m just being honest about how amazing you are.",
  "You make everything around you shine.",
  "Are you a song? Because I can’t get you out of my head.",
  "I didn’t know beauty had a name until today.",
  "Do you have a map? I keep getting lost in your eyes.",
  "I’m not usually smooth, but for you I can try.",
  "I could get lost in your laugh forever.",
  "You’re the vibe I’ve been looking for.",
  "Your presence is magnetic.",
  "I don’t need a reason to talk to you — just you is enough.",
  "Are you a painting? Because I could stare at you all day.",
  "Your smile should be illegal — it’s that good.",
  "I must be dreaming… you’re unreal.",
  "I didn’t believe in magic until I met you.",
  "You’ve got style, charm, and the kind of smile that melts hearts.",
  "I could spend all night just listening to you talk.",
  "Are you a star? Because you light up the room.",
  "Your vibe is unmatched.",
  "I can’t tell if it’s the room or just you, but it’s hot.",
  "You’ve got that something that words can’t describe.",
  "You make ordinary moments extraordinary.",
  "I’m not trying to impress… but it seems I already am.",
  "Your energy makes the world brighter.",
  "Are you a magnet? Because I feel pulled toward you.",
  "You’ve got that effortless charm.",
  "You’re the reason good things happen to people.",
  "Every time you speak, it’s like poetry.",
  "I didn’t believe in chemistry until now.",
  "Your laugh could start a revolution.",
  "You’ve got elegance and fire all in one.",
  "You turn simple moments into memories.",
  "I feel lucky just standing near you.",
  "Your aura is unforgettable.",
  "I can’t look away from you.",
  "You’re the highlight of this day.",
  "Are you a melody? Because you play softly in my heart.",
  "You’re a vibe I can’t resist.",
  "Your eyes tell stories no one else can read.",
  "I’ve never met someone with your energy.",
  "You make the impossible look easy.",
  "You’ve got confidence and charm rolled into one.",
  "Your smile is my new favorite view.",
  "You make hearts skip beats effortlessly.",
  "I could watch you for hours and never get bored.",
  "You bring warmth into every room you enter.",
  "I don’t need words when your presence speaks volumes.",
  "Are you a dream? Because I don’t want to wake up.",
  "You’ve got that mysterious vibe I can’t ignore.",
  "Every move you make is captivating.",
  "You make elegance look effortless.",
  "Your style and energy are next-level.",
  "You’re the reason people believe in magic.",
  "I could listen to your voice forever.",
  "You’ve got charm in every glance.",
  "I didn’t know grace had a face until today.",
  "Your energy makes everything better.",
  "Are you a spark? Because you light up everything.",
  "You’ve got that smooth vibe I admire.",
  "Every moment with you feels cinematic.",
  "You’ve got beauty, brains, and charm.",
  "You’re effortlessly unforgettable.",
  "I could follow you anywhere just to feel this vibe.",
  "You make simple things look extraordinary.",
  "Your aura is magnetic.",
  "You’ve got a presence that turns heads.",
  "I’ve never met someone as smooth as you.",
  "You’re a masterpiece in motion.",
  "Every time you smile, the world changes.",
  "You’ve got the kind of charm that sticks.",
  "You make elegance and allure look easy.",
  "I could get lost in your energy all day.",
  "Your vibe is intoxicating.",
  "You turn casual moments into memories.",
  "Your confidence is irresistible.",
  "Every word you say leaves an impact.",
  "You’re unforgettable in every sense.",
  "You’ve got the kind of energy that lingers.",
  "You make hearts race without trying.",
  "Your presence is magnetic and smooth.",
  "I could watch your style all day.",
  "You bring calm and excitement at the same time.",
  "You make ordinary moments feel special.",
  "Every glance from you is a story.",
  "You’re effortlessly captivating.",
  "I could get lost in your charm forever.",
  "You’ve got that smooth energy that’s rare.",
  "I’ve never felt a vibe like yours before.",
  "You make elegance and magnetism look easy.",
  "Your energy leaves a mark on everyone around you.",
  "You’re the kind of smooth people write songs about.",
  "I could follow your lead anywhere.",
  "Your vibe is unmatched and unforgettable.",
  "You make hearts skip without trying.",
  "You’re the highlight of any moment.",
  "Every smile of yours is iconic.",
  "You’ve got that effortless allure everyone notices.",
  "I could spend forever admiring your style.", "Let me borrow a moment.", "You look like good timing.",  "Are you a keyboard? Because you’re just my type.",
  "Do you have a map? I keep getting lost in your smile.",
  "Are you Wi-Fi? Because I feel a strong connection.",
  "Are you a magician? Because whenever I look at you, everyone else disappears.",
  "Is your dad a boxer? Because you’re a knockout!",
  "Do you like Star Wars? Because Yoda one for me.",
  "Are you French? Because Eiffel for you.",
  "Do you have a Band-Aid? I just scraped my knee falling for you.",
  "Are you a parking ticket? Because you’ve got FINE written all over you.",
  "Are you made of copper and tellurium? Because you’re Cu-Te.",
  "If you were a vegetable, you’d be a cute-cumber.",
  "Are you a bank loan? Because you have my interest.",
  "Do you have a sunburn, or are you always this hot?",
  "Are you a cat? Because I’m feline a connection here.",
  "Are you a Wi-Fi signal? Because I’m feeling a strong connection.",
  "Are you a magician’s assistant? Because you just made my heart disappear.",
  "If you were a fruit, you’d be a fine-apple.",
  "Are you a camera? Because I can smile every time I see you.",
  "Are you a campfire? Because you’re hot and I want s’more.",
  "Do you like raisins? How do you feel about a date?",
  "Are you a candy? Because you’re sweet enough to give me a sugar rush.",
  "Are you a cookie? Because I can’t resist you.",
  "Are you a donut? Because I donut want anyone else.",
  "Are you a bubble? Because you make life more fun.",
  "Are you a cupcake? Because you’re sweet and I want more.",
  "Are you a banana? Because I find you a-peeling.",
  "Are you a magician? Because every time you’re around, things disappear… my focus, my will, my time.",
  "Are you an alien? Because you just abducted my heart.",
  "Are you a light bulb? Because you brighten my day.",
  "Are you a rainbow? Because you color my world.",
  "Are you an emoji? Because you complete my messages.",
  "Are you a cloud? Because I feel lighter when I’m around you.",
  "Are you a cookie jar? Because I want to dig in.",
  "Are you a pen? Because you write happiness in my life.",
  "Are you a pillow? Because I want to lay with you all day.",
  "Are you a cupcake? Because you’re the icing on my day.",
  "Are you coffee? Because you perk me up.",
  "Are you chocolate? Because you melt my heart.",
  "Are you a rainbow? Because you make life colorful.",
  "Are you glitter? Because you sparkle everywhere.",
  "Are you sugar? Because you’re sweet on me.",
  "Are you pizza? Because I want a slice of you.",
  "Are you a firework? Because you light up my night.",
  "Are you a spark? Because you ignite my soul.",
  "Are you a camera? Because every time I see you, I smile.",
  "Are you a balloon? Because you lift me up.",
  "Are you popcorn? Because you make life fun.",
  "Are you a treasure? Because I’ve been searching for you.",
  "Are you a sparkler? Because you make life shine.",
  "Are you a key? Because you unlock my heart.",
  "Are you a mirror? Because I see myself in you.",
  "Are you candy floss? Because life is sweeter with you.",
  "Are you a bubble gum? Because I can’t stop sticking around you.",
  "Are you a jellybean? Because you’re sweet and colorful.",
  "Are you a cupcake? Because you make my day sweeter.",
  "Are you a cat meme? Because you just made me laugh uncontrollably.",
  "Are you a Wi-Fi password? Because I’m really trying to connect.",
  "Are you a sticker? Because you make everything better.",
  "Are you a donut? Because you’ve got a hole in my heart.",
  "Are you a sock? Because I think we’d make a cute pair.",
  "Are you a pancake? Because you’re flipping amazing.",
  "Are you a pizza topping? Because you complete me.",
  "Are you a superhero? Because you just saved my day.",
  "Are you a candle? Because you light up the room.",
  "Are you a keyboard? Because you add meaning to my life.",
  "Are you a hot chocolate? Because you’re warm and sweet.",
  "Are you a pillow? Because I want to hug you all night.",
  "Are you a pen? Because you write joy in my life.",
  "Are you a spoon? Because you complete my cereal.",
  "Are you a selfie? Because I can’t stop looking at you.",
  "Are you a magnet? Because I’m attracted to you.",
  "Are you a rainbow? Because you brighten my stormy days.",
  "Are you a star? Because I wish on you every night.",
  "Are you a cloud? Because you’re floating in my thoughts.",
  "Are you a key? Because you unlock my happiness.",
  "Are you a smoothie? Because you blend perfectly with me.",
  "Are you a marshmallow? Because you’re soft and sweet.",
  "Are you a beach? Because I’m lost in your waves.",
  "Are you a pillow? Because I dream about you.",
  "Are you a donut? Because you’re a hole lot of fun.",
  "Are you a joke? Because you make me laugh uncontrollably.",
  "Are you a meme? Because I want to share you with everyone.",
  "Are you a video game? Because I can’t stop playing with you.",
  "Are you a latte? Because you’re steaming hot and sweet.",
  "Are you a movie? Because I want to watch you again and again.",
  "Are you a joke? Because I keep thinking about you.",
  "Are you a sock? Because I can’t find anyone else to match.",
  "Are you a cat video? Because I can watch you forever.",
  "Are you a pancake? Because you flip my world around.",
  "Are you a cupcake? Because life is sweeter with you.",
  "Are you a sparkler? Because you make nights brighter.",
  "Are you a hotdog? Because you’re a classic I can’t resist.",
  "Are you popcorn? Because I want to share you with everyone.",
  "Are you a joke book? Because I laugh every time you’re around.",
  "Are you a candy bar? Because you’re my sweet escape.",
  "Are you ice cream? Because I melt in your presence.",
  "Are you a latte? Because life’s better with you.",
  "Are you a Wi-Fi signal? Because I’m constantly connecting.",
  "Are you a donut? Because you’ve got my heart filled.",
  "Are you a balloon? Because you make my spirits lift.",
  "Are you a cat? Because I’m pawsitively in love with you.",
  "Are you a rainbow? Because you color my world.",
  "Are you a marshmallow? Because you stick to my heart.", "You’re calm, confident, and dangerous.", "That smile should be illegal." ],
  funny:[ "Are you a magician? Because whenever I look at you, everyone else disappears… and I panic!",  "Are you a keyboard? Because you’re just my type.",
  "Do you have a map? I keep getting lost in your smile.",
  "Are you Wi-Fi? Because I feel a strong connection.",
  "Are you a magician? Because whenever I look at you, everyone else disappears.",
  "Is your dad a boxer? Because you’re a knockout!",
  "Do you like Star Wars? Because Yoda one for me.",
  "Are you French? Because Eiffel for you.",
  "Do you have a Band-Aid? I just scraped my knee falling for you.",
  "Are you a parking ticket? Because you’ve got FINE written all over you.",
  "Are you made of copper and tellurium? Because you’re Cu-Te.",
  "If you were a vegetable, you’d be a cute-cumber.",
  "Are you a bank loan? Because you have my interest.",
  "Do you have a sunburn, or are you always this hot?",
  "Are you a cat? Because I’m feline a connection here.",
  "Are you a Wi-Fi signal? Because I’m feeling a strong connection.",
  "Are you a magician’s assistant? Because you just made my heart disappear.",
  "If you were a fruit, you’d be a fine-apple.",
  "Are you a camera? Because I can smile every time I see you.",
  "Are you a campfire? Because you’re hot and I want s’more.",
  "Do you like raisins? How do you feel about a date?",
  "Are you a candy? Because you’re sweet enough to give me a sugar rush.",
  "Are you a cookie? Because I can’t resist you.",
  "Are you a donut? Because I donut want anyone else.",
  "Are you a bubble? Because you make life more fun.",
  "Are you a cupcake? Because you’re sweet and I want more.",
  "Are you a banana? Because I find you a-peeling.",
  "Are you a magician? Because every time you’re around, things disappear… my focus, my will, my time.",
  "Are you an alien? Because you just abducted my heart.",
  "Are you a light bulb? Because you brighten my day.",
  "Are you a rainbow? Because you color my world.",
  "Are you an emoji? Because you complete my messages.",
  "Are you a cloud? Because I feel lighter when I’m around you.",
  "Are you a cookie jar? Because I want to dig in.",
  "Are you a pen? Because you write happiness in my life.",
  "Are you a pillow? Because I want to lay with you all day.",
  "Are you a cupcake? Because you’re the icing on my day.",
  "Are you coffee? Because you perk me up.",
  "Are you chocolate? Because you melt my heart.",
  "Are you a rainbow? Because you make life colorful.",
  "Are you glitter? Because you sparkle everywhere.",
  "Are you sugar? Because you’re sweet on me.",
  "Are you pizza? Because I want a slice of you.",
  "Are you a firework? Because you light up my night.",
  "Are you a spark? Because you ignite my soul.",
  "Are you a camera? Because every time I see you, I smile.",
  "Are you a balloon? Because you lift me up.",
  "Are you popcorn? Because you make life fun.",
  "Are you a treasure? Because I’ve been searching for you.",
  "Are you a sparkler? Because you make life shine.",
  "Are you a key? Because you unlock my heart.",
  "Are you a mirror? Because I see myself in you.",
  "Are you candy floss? Because life is sweeter with you.",
  "Are you a bubble gum? Because I can’t stop sticking around you.",
  "Are you a jellybean? Because you’re sweet and colorful.",
  "Are you a cupcake? Because you make my day sweeter.",
  "Are you a cat meme? Because you just made me laugh uncontrollably.",
  "Are you a Wi-Fi password? Because I’m really trying to connect.",
  "Are you a sticker? Because you make everything better.",
  "Are you a donut? Because you’ve got a hole in my heart.",
  "Are you a sock? Because I think we’d make a cute pair.",
  "Are you a pancake? Because you’re flipping amazing.",
  "Are you a pizza topping? Because you complete me.",
  "Are you a superhero? Because you just saved my day.",
  "Are you a candle? Because you light up the room.",
  "Are you a keyboard? Because you add meaning to my life.",
  "Are you a hot chocolate? Because you’re warm and sweet.",
  "Are you a pillow? Because I want to hug you all night.",
  "Are you a pen? Because you write joy in my life.",
  "Are you a spoon? Because you complete my cereal.",
  "Are you a selfie? Because I can’t stop looking at you.",
  "Are you a magnet? Because I’m attracted to you.",
  "Are you a rainbow? Because you brighten my stormy days.",
  "Are you a star? Because I wish on you every night.",
  "Are you a cloud? Because you’re floating in my thoughts.",
  "Are you a key? Because you unlock my happiness.",
  "Are you a smoothie? Because you blend perfectly with me.",
  "Are you a marshmallow? Because you’re soft and sweet.",
  "Are you a beach? Because I’m lost in your waves.",
  "Are you a pillow? Because I dream about you.",
  "Are you a donut? Because you’re a hole lot of fun.",
  "Are you a joke? Because you make me laugh uncontrollably.",
  "Are you a meme? Because I want to share you with everyone.",
  "Are you a video game? Because I can’t stop playing with you.",
  "Are you a latte? Because you’re steaming hot and sweet.",
  "Are you a movie? Because I want to watch you again and again.",
  "Are you a joke? Because I keep thinking about you.",
  "Are you a sock? Because I can’t find anyone else to match.",
  "Are you a cat video? Because I can watch you forever.",
  "Are you a pancake? Because you flip my world around.",
  "Are you a cupcake? Because life is sweeter with you.",
  "Are you a sparkler? Because you make nights brighter.",
  "Are you a hotdog? Because you’re a classic I can’t resist.",
  "Are you popcorn? Because I want to share you with everyone.",
  "Are you a joke book? Because I laugh every time you’re around.",
  "Are you a candy bar? Because you’re my sweet escape.",
  "Are you ice cream? Because I melt in your presence.",
  "Are you a latte? Because life’s better with you.",
  "Are you a Wi-Fi signal? Because I’m constantly connecting.",
  "Are you a donut? Because you’ve got my heart filled.",
  "Are you a balloon? Because you make my spirits lift.",
  "Are you a cat? Because I’m pawsitively in love with you.",
  "Are you a rainbow? Because you color my world.",
  "Are you a marshmallow? Because you stick to my heart.", "Do you have a name or can I call you mine… awkwardly?", "Are you French? Because Eiffel for you.", "Do you like Star Wars? Because Yoda one for me!", "Are you a loan? Because you have my interest… and my credit score." ],
  instagram:[ "Living my best life, one selfie at a time.","Life isn’t about waiting for the storm to pass, it’s about learning to dance in the rain.",
"Do what you can, with what you have, where you are.",
"Believe you can and you’re halfway there.",
"Don’t watch the clock; do what it does. Keep going.",
"The only limit to our realization of tomorrow is our doubts of today.",
"Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
"Success is not final, failure is not fatal: it is the courage to continue that counts.",
"Hardships often prepare ordinary people for an extraordinary destiny.",
"The best way to predict the future is to create it.",
"Believe in yourself and all that you are.",
"Act as if what you do makes a difference. It does.",
"Don’t wait for opportunity. Create it.",
"The only way to achieve the impossible is to believe it is possible.",
"Your limitation—it’s only your imagination.",
"Push yourself, because no one else is going to do it for you.",
"Great things never come from comfort zones.",
"Dream it. Wish it. Do it.",
"Sometimes later becomes never. Do it now.",
"Don’t stop when you’re tired. Stop when you’re done.",
"The harder you work for something, the greater you’ll feel when you achieve it.",
"Dream bigger. Do bigger.",
"Don’t wait for the perfect moment. Take the moment and make it perfect.",
"Little things make big days.",
"It’s going to be hard, but hard does not mean impossible.",
"Don’t limit your challenges. Challenge your limits.",
"Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
"The key to success is to focus on goals, not obstacles.",
"Great things are done by a series of small things brought together.",
"Work hard in silence, let success make the noise.",
"Don’t be afraid to give up the good to go for the great.",
"Success doesn’t just find you. You have to go out and get it.",
"Don’t wait. The time will never be just right.",
"Do something today that your future self will thank you for.",
"Don’t be busy, be productive.",
"The way to get started is to quit talking and begin doing.",
"Strive not to be a success, but rather to be of value.",
"Keep going. Be all in.",
"You are capable of amazing things.",
"The difference between ordinary and extraordinary is that little extra.",
"Your only limit is you.",
"Don’t watch others, run your own race.",
"Failure will never overtake me if my determination to succeed is strong enough.",
"Stay positive, work hard, make it happen.",
"The expert in anything was once a beginner.",
"Motivation is what gets you started. Habit is what keeps you going.",
"Don’t wait for opportunities, create them.",
"Push yourself because no one else is going to do it for you.",
"Great things take time. Be patient.",
"Success is the sum of small efforts, repeated day in and day out.",
"Discipline is choosing between what you want now and what you want most.",
"Don’t be afraid of being different. Be afraid of being the same as everyone else.",
"Don’t count the days, make the days count.",
"Opportunities don’t happen. You create them.",
"Be not afraid of life. Believe that life is worth living, and your belief will help create the fact.",
"Your dream doesn’t have an expiration date. Take a deep breath and try again.",
"Success is not in what you have, but who you are.",
"Do what you love and never work a day in your life.",
"You don’t have to be great to start, but you have to start to be great.",
"Don’t let yesterday take up too much of today.",
"You are never too old to set another goal or to dream a new dream.",
"Everything you’ve ever wanted is on the other side of fear.",
"Success is walking from failure to failure with no loss of enthusiasm.",
"It always seems impossible until it’s done.",
"Start where you are. Use what you have. Do what you can.",
"Your life does not get better by chance, it gets better by change.",
"Challenges are what make life interesting. Overcoming them is what makes life meaningful.",
"The only person you are destined to become is the person you decide to be.",
"The harder the battle, the sweeter the victory.",
"Don’t let what you cannot do interfere with what you can do.",
"Success isn’t overnight. It’s when every day you get a little better than the day before.",
"The best revenge is massive success.",
"Success usually comes to those who are too busy to be looking for it.",
"Don’t be afraid to start over. It’s a chance to rebuild what you want.",
"Focus on being productive instead of busy.",
"Your time is limited, don’t waste it living someone else’s life.",
"Everything you can imagine is real.",
"Do one thing every day that scares you.",
"Turn your wounds into wisdom.",
"Strive for progress, not perfection.",
"Great minds discuss ideas; average minds discuss events; small minds discuss people.",
"It does not matter how slowly you go as long as you do not stop.",
"Motivation is what gets you started. Habit is what keeps you going.",
"The secret of getting ahead is getting started.",
"The only thing standing between you and your goal is the story you keep telling yourself as to why you can’t achieve it.",
"The best way to get started is to quit talking and begin doing.",
"Start by doing what’s necessary; then do what’s possible; and suddenly you are doing the impossible.",
"Don’t let what you cannot do interfere with what you can do.",
"Believe you can and you’re halfway there.",
"Success is not in what you have, but who you are.",
"You are braver than you believe, stronger than you seem, and smarter than you think.",
"Your attitude determines your direction.",
"Good things come to people who wait, but better things come to those who go out and get them.",
"Stop being afraid of what could go wrong and think of what could go right.",
"Small steps every day lead to big results.",
"Don’t wait for opportunity. Create it.",
"Be yourself; everyone else is already taken.",
"Failure is not the opposite of success; it’s part of success.",
"Success is how high you bounce when you hit bottom.",
"Your limitation—it’s only your imagination.",
"Push yourself, because no one else is going to do it for you.",
"Great things never come from comfort zones.",
"Dream it. Wish it. Do it.",
"Sometimes later becomes never. Do it now.",
"Don’t stop when you’re tired. Stop when you’re done.",
"The harder you work for something, the greater you’ll feel when you achieve it.",
"Dream bigger. Do bigger.",
"Don’t wait for the perfect moment. Take the moment and make it perfect.",
"Little things make big days.",
"It’s going to be hard, but hard does not mean impossible.",
"Don’t limit your challenges. Challenge your limits.",
"Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
"The key to success is to focus on goals, not obstacles.",
"Great things are done by a series of small things brought together.",
"Work hard in silence, let success make the noise.",
"Don’t be afraid to give up the good to go for the great.",
"Success doesn’t just find you. You have to go out and get it.",
"Don’t wait. The time will never be just right.",
"Do something today that your future self will thank you for.",
"Don’t be busy, be productive.",
"The way to get started is to quit talking and begin doing.",
"Strive not to be a success, but rather to be of value.",
"Keep going. Be all in.",
"You are capable of amazing things.",
"The difference between ordinary and extraordinary is that little extra.",
"Your only limit is you.",
"Don’t watch others, run your own race.",
"Failure will never overtake me if my determination to succeed is strong enough.",
"Stay positive, work hard, make it happen.",
"The expert in anything was once a beginner.",
"Motivation is what gets you started. Habit is what keeps you going.",
"Push yourself because no one else is going to do it for you.",
"Great things take time. Be patient.",
"Success is the sum of small efforts, repeated day in and day out.",
"Discipline is choosing between what you want now and what you want most.",
"Don’t be afraid of being different. Be afraid of being the same as everyone else.",
"Don’t count the days, make the days count.",
"Opportunities don’t happen. You create them.",
"Be not afraid of life. Believe that life is worth living, and your belief will help create the fact.",
"Your dream doesn’t have an expiration date. Take a deep breath and try again.",
"Success is not in what you have, but who you are.",
"Do what you love and never work a day in your life.",
"You don’t have to be great to start, but you have to start to be great.",
"Don’t let yesterday take up too much of today.",
"You are never too old to set another goal or to dream a new dream.",
"Everything you’ve ever wanted is on the other side of fear.",
"Success is walking from failure to failure with no loss of enthusiasm.",
"It always seems impossible until it’s done.",
"Start where you are. Use what you have. Do what you can.",
"Your life does not get better by chance, it gets better by change.",
"Challenges are what make life interesting. Overcoming them is what makes life meaningful.",
"The only person you are destined to become is the person you decide to be.",
"The harder the battle, the sweeter the victory.",
"Don’t let what you cannot do interfere with what you can do.",
"Success isn’t overnight. It’s when every day you get a little better than the day before.",
"The best revenge is massive success.",
"Success usually comes to those who are too busy to be looking for it.",
"Don’t be afraid to start over. It’s a chance to rebuild what you want.",
"Focus on being productive instead of busy.",
"Your time is limited, don’t waste it living someone else’s life.",
"Everything you can imagine is real.",
"Do one thing every day that scares you.",
"Turn your wounds into wisdom.",
"Strive for progress, not perfection.",
"Great minds discuss ideas; average minds discuss events; small minds discuss people.",
"It does not matter how slowly you go as long as you do not stop.", "Coffee in one hand, confidence in the other.", "Smile big, laugh often, live fully.", "Chasing dreams and catching vibes.", "Just me, creating my own sunshine." ]
};

// Quotes of the Day
const quotes=[ "Be yourself; everyone else is already taken.","Life isn’t about waiting for the storm to pass, it’s about learning to dance in the rain.",
"Do what you can, with what you have, where you are.",
"Believe you can and you’re halfway there.",
"Don’t watch the clock; do what it does. Keep going.",
"The only limit to our realization of tomorrow is our doubts of today.",
"Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
"Success is not final, failure is not fatal: it is the courage to continue that counts.",
"Hardships often prepare ordinary people for an extraordinary destiny.",
"The best way to predict the future is to create it.",
"Believe in yourself and all that you are.",
"Act as if what you do makes a difference. It does.",
"Don’t wait for opportunity. Create it.",
"The only way to achieve the impossible is to believe it is possible.",
"Your limitation—it’s only your imagination.",
"Push yourself, because no one else is going to do it for you.",
"Great things never come from comfort zones.",
"Dream it. Wish it. Do it.",
"Sometimes later becomes never. Do it now.",
"Don’t stop when you’re tired. Stop when you’re done.",
"The harder you work for something, the greater you’ll feel when you achieve it.",
"Dream bigger. Do bigger.",
"Don’t wait for the perfect moment. Take the moment and make it perfect.",
"Little things make big days.",
"It’s going to be hard, but hard does not mean impossible.",
"Don’t limit your challenges. Challenge your limits.",
"Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
"The key to success is to focus on goals, not obstacles.",
"Great things are done by a series of small things brought together.",
"Work hard in silence, let success make the noise.",
"Don’t be afraid to give up the good to go for the great.",
"Success doesn’t just find you. You have to go out and get it.",
"Don’t wait. The time will never be just right.",
"Do something today that your future self will thank you for.",
"Don’t be busy, be productive.",
"The way to get started is to quit talking and begin doing.",
"Strive not to be a success, but rather to be of value.",
"Keep going. Be all in.",
"You are capable of amazing things.",
"The difference between ordinary and extraordinary is that little extra.",
"Your only limit is you.",
"Don’t watch others, run your own race.",
"Failure will never overtake me if my determination to succeed is strong enough.",
"Stay positive, work hard, make it happen.",
"The expert in anything was once a beginner.",
"Motivation is what gets you started. Habit is what keeps you going.",
"Don’t wait for opportunities, create them.",
"Push yourself because no one else is going to do it for you.",
"Great things take time. Be patient.",
"Success is the sum of small efforts, repeated day in and day out.",
"Discipline is choosing between what you want now and what you want most.",
"Don’t be afraid of being different. Be afraid of being the same as everyone else.",
"Don’t count the days, make the days count.",
"Opportunities don’t happen. You create them.",
"Be not afraid of life. Believe that life is worth living, and your belief will help create the fact.",
"Your dream doesn’t have an expiration date. Take a deep breath and try again.",
"Success is not in what you have, but who you are.",
"Do what you love and never work a day in your life.",
"You don’t have to be great to start, but you have to start to be great.",
"Don’t let yesterday take up too much of today.",
"You are never too old to set another goal or to dream a new dream.",
"Everything you’ve ever wanted is on the other side of fear.",
"Success is walking from failure to failure with no loss of enthusiasm.",
"It always seems impossible until it’s done.",
"Start where you are. Use what you have. Do what you can.",
"Your life does not get better by chance, it gets better by change.",
"Challenges are what make life interesting. Overcoming them is what makes life meaningful.",
"The only person you are destined to become is the person you decide to be.",
"The harder the battle, the sweeter the victory.",
"Don’t let what you cannot do interfere with what you can do.",
"Success isn’t overnight. It’s when every day you get a little better than the day before.",
"The best revenge is massive success.",
"Success usually comes to those who are too busy to be looking for it.",
"Don’t be afraid to start over. It’s a chance to rebuild what you want.",
"Focus on being productive instead of busy.",
"Your time is limited, don’t waste it living someone else’s life.",
"Everything you can imagine is real.",
"Do one thing every day that scares you.",
"Turn your wounds into wisdom.",
"Strive for progress, not perfection.",
"Great minds discuss ideas; average minds discuss events; small minds discuss people.",
"It does not matter how slowly you go as long as you do not stop.",
"Motivation is what gets you started. Habit is what keeps you going.",
"The secret of getting ahead is getting started.",
"The only thing standing between you and your goal is the story you keep telling yourself as to why you can’t achieve it.",
"The best way to get started is to quit talking and begin doing.",
"Start by doing what’s necessary; then do what’s possible; and suddenly you are doing the impossible.",
"Don’t let what you cannot do interfere with what you can do.",
"Believe you can and you’re halfway there.",
"Success is not in what you have, but who you are.",
"You are braver than you believe, stronger than you seem, and smarter than you think.",
"Your attitude determines your direction.",
"Good things come to people who wait, but better things come to those who go out and get them.",
"Stop being afraid of what could go wrong and think of what could go right.",
"Small steps every day lead to big results.",
"Don’t wait for opportunity. Create it.",
"Be yourself; everyone else is already taken.",
"Failure is not the opposite of success; it’s part of success.",
"Success is how high you bounce when you hit bottom.",
"Your limitation—it’s only your imagination.",
"Push yourself, because no one else is going to do it for you.",
"Great things never come from comfort zones.",
"Dream it. Wish it. Do it.",
"Sometimes later becomes never. Do it now.",
"Don’t stop when you’re tired. Stop when you’re done.",
"The harder you work for something, the greater you’ll feel when you achieve it.",
"Dream bigger. Do bigger.",
"Don’t wait for the perfect moment. Take the moment and make it perfect.",
"Little things make big days.",
"It’s going to be hard, but hard does not mean impossible.",
"Don’t limit your challenges. Challenge your limits.",
"Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
"The key to success is to focus on goals, not obstacles.",
"Great things are done by a series of small things brought together.",
"Work hard in silence, let success make the noise.",
"Don’t be afraid to give up the good to go for the great.",
"Success doesn’t just find you. You have to go out and get it.",
"Don’t wait. The time will never be just right.",
"Do something today that your future self will thank you for.",
"Don’t be busy, be productive.",
"The way to get started is to quit talking and begin doing.",
"Strive not to be a success, but rather to be of value.",
"Keep going. Be all in.",
"You are capable of amazing things.",
"The difference between ordinary and extraordinary is that little extra.",
"Your only limit is you.",
"Don’t watch others, run your own race.",
"Failure will never overtake me if my determination to succeed is strong enough.",
"Stay positive, work hard, make it happen.",
"The expert in anything was once a beginner.",
"Motivation is what gets you started. Habit is what keeps you going.",
"Push yourself because no one else is going to do it for you.",
"Great things take time. Be patient.",
"Success is the sum of small efforts, repeated day in and day out.",
"Discipline is choosing between what you want now and what you want most.",
"Don’t be afraid of being different. Be afraid of being the same as everyone else.",
"Don’t count the days, make the days count.",
"Opportunities don’t happen. You create them.",
"Be not afraid of life. Believe that life is worth living, and your belief will help create the fact.",
"Your dream doesn’t have an expiration date. Take a deep breath and try again.",
"Success is not in what you have, but who you are.",
"Do what you love and never work a day in your life.",
"You don’t have to be great to start, but you have to start to be great.",
"Don’t let yesterday take up too much of today.",
"You are never too old to set another goal or to dream a new dream.",
"Everything you’ve ever wanted is on the other side of fear.",
"Success is walking from failure to failure with no loss of enthusiasm.",
"It always seems impossible until it’s done.",
"Start where you are. Use what you have. Do what you can.",
"Your life does not get better by chance, it gets better by change.",
"Challenges are what make life interesting. Overcoming them is what makes life meaningful.",
"The only person you are destined to become is the person you decide to be.",
"The harder the battle, the sweeter the victory.",
"Don’t let what you cannot do interfere with what you can do.",
"Success isn’t overnight. It’s when every day you get a little better than the day before.",
"The best revenge is massive success.",
"Success usually comes to those who are too busy to be looking for it.",
"Don’t be afraid to start over. It’s a chance to rebuild what you want.",
"Focus on being productive instead of busy.",
"Your time is limited, don’t waste it living someone else’s life.",
"Everything you can imagine is real.",
"Do one thing every day that scares you.",
"Turn your wounds into wisdom.",
"Strive for progress, not perfection.",
"Great minds discuss ideas; average minds discuss events; small minds discuss people.",
"It does not matter how slowly you go as long as you do not stop.", "Do more of what makes you happy.", "Stay positive, work hard, make it happen.", "Dream big and dare to fail.", "Happiness is a journey, not a destination." ];

// Popular lines tracker
let popularLines={};

// User submitted lines
let userLines=[];

// Current mood
let currentMood="playful"; // default

// Set mood
function setMood(mood){
  currentMood=mood;
  document.getElementById("mood-title").innerText=`Your ${mood.charAt(0).toUpperCase()+mood.slice(1)} Line:`;
  generateLine();
}

// Generate line
function generateLine(){
  const moodLines=lines[currentMood];
  if(!moodLines || moodLines.length===0) return;
  const randomLine=moodLines[Math.floor(Math.random()*moodLines.length)];
  const lineBox=document.getElementById("line-box");
  lineBox.innerText=randomLine;

  // Track popularity
  popularLines[randomLine]=popularLines[randomLine]?popularLines[randomLine]+1:1;
  updatePopular();
}

// Copy line
function copyLine(element){
  const text=element.innerText;
  navigator.clipboard.writeText(text);
  element.innerText="Copied 😎";
  setTimeout(()=>{ element.innerText=text },900);

  // Track popularity
  popularLines[text]=popularLines[text]?popularLines[text]+1:1;
  updatePopular();
}

// Update popular lines
function updatePopular(){
  const popular=Object.entries(popularLines).sort((a,b)=>b[1]-a[1]).slice(0,5);
  const ul=document.getElementById("popular-lines");
  ul.innerHTML="";
  popular.forEach(([line,count])=>{
    const li=document.createElement("li");
    li.innerText=`${line} (${count} copies)`;
    ul.appendChild(li);
  });
}

// Generate random quote
function generateQuote(){
  const quote=quotes[Math.floor(Math.random()*quotes.length)];
  document.getElementById("quote-box").innerText=quote;
}

// Dark Mode toggle
function toggleDark(){
  document.body.classList.toggle("dark-mode");
}

// Share Buttons
function shareWhatsApp(){
  const text=document.getElementById("line-box").innerText;
  window.open(`https://wa.me/?text=${encodeURIComponent(text)}`,'_blank');
}

function shareInstagram(){
  const text=document.getElementById("line-box").innerText;
  alert("Copy the line to post on Instagram: "+text);
}

function shareTikTok(){
  const text=document.getElementById("line-box").innerText;
  alert("Copy the line to use in TikTok caption: "+text);
}

// User submitted lines
function submitLine(){
  const input=document.getElementById("user-line-input");
  const text=input.value.trim();
  if(text==="") return alert("Type a line first!");
  userLines.push(text);
  const ul=document.getElementById("user-lines-list");
  const li=document.createElement("li");
  li.innerText=text;
  ul.appendChild(li);
  input.value="";
}

// Mashup generator
function generateMashup(){
  const allLines=[...lines.playful,...lines.confident,...lines.smooth,...lines.funny];
  const first=allLines[Math.floor(Math.random()*allLines.length)];
  let second=allLines[Math.floor(Math.random()*allLines.length)];
  while(second===first) second=allLines[Math.floor(Math.random()*allLines.length)];
  document.getElementById("mashup-box").innerText=`${first} / ${second}`;
}

// Auto-generate initial line & quote on page load
window.onload = function(){
  setMood(currentMood); // default playful
  generateQuote();
  generateMashup();
};
// WhatsApp Share
function shareWhatsApp() {
  const text = document.getElementById("line-box").innerText;
  if (!text) return alert("No line to share!");
  // WhatsApp web / app link
  const url = `https://wa.me/?text=${encodeURIComponent(text)}`;
  window.open(url, "_blank");
}

// Instagram Share (copy text + link to Instagram profile)
function shareInstagram() {
  const text = document.getElementById("line-box").innerText;
  if (!text) return alert("No line to share!");
  // Instagram does not allow direct text sharing, so we copy to clipboard
  navigator.clipboard.writeText(text).then(() => {
    alert("Copied to clipboard! Open Instagram and paste it in your story, bio, or post.");
    window.open("https://www.instagram.com", "_blank"); // Opens Instagram website
  });
}

// TikTok Share (copy text + open TikTok)
function shareTikTok() {
  const text = document.getElementById("line-box").innerText;
  if (!text) return alert("No line to share!");
  // TikTok cannot accept direct text via URL, copy instead
  navigator.clipboard.writeText(text).then(() => {
    alert("Copied to clipboard! Open TikTok and paste it in your caption or bio.");
    window.open("https://www.tiktok.com", "_blank"); // Opens TikTok website
  });
}
